# Generated by Django 4.0.3 on 2022-03-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название', verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание')),
                ('color', models.TextField(blank=True, default='#fff', help_text='Цвет', null=True, verbose_name='Цвет')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', related_query_name='children', to='core.businessdomains')),
            ],
            options={
                'verbose_name': 'Бизнес домен',
                'verbose_name_plural': 'Бизнес домены',
                'db_table': 'business_domains',
            },
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название', verbose_name='Название')),
                ('business_name', models.TextField(blank=True, help_text='Бизнес название', null=True, verbose_name='Бизнес название')),
                ('color', models.TextField(blank=True, default='#fff', help_text='Цвет', null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'db_table': 'tables',
            },
        ),
        migrations.CreateModel(
            name='TablesInDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_domain', models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, to='core.businessdomains')),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, to='core.tables')),
            ],
            options={
                'verbose_name': 'Таблица связка таблиц и доменов',
                'verbose_name_plural': 'Таблица связка таблиц и доменов',
                'db_table': 'tables_in_domains',
            },
        ),
        migrations.AddField(
            model_name='businessdomains',
            name='tables',
            field=models.ManyToManyField(related_name='business_domains', related_query_name='business_domains', through='core.TablesInDomains', to='core.tables'),
        ),
    ]
