# Generated by Django 4.0.3 on 2022-03-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesindomains',
            name='business_domain',
            field=models.ForeignKey(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, related_name='tables_in_domains', related_query_name='tables_in_domains', to='core.businessdomains'),
        ),
        migrations.AlterField(
            model_name='tablesindomains',
            name='table',
            field=models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, related_name='tables_in_domains', related_query_name='tables_in_domains', to='core.tables'),
        ),
    ]
