# Generated by Django 4.0.3 on 2022-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tags_tables_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание'),
        ),
    ]
