# Generated by Django 4.0.3 on 2022-04-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tags_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdomains',
            name='tags',
            field=models.ManyToManyField(related_name='domains', related_query_name='domains', to='core.tags'),
        ),
    ]
