# Generated by Django 4.0.3 on 2022-04-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_businessdomains_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomains',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='domains', related_query_name='domains', to='core.tags'),
        ),
    ]
