# Generated by Django 4.0.3 on 2022-04-24 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_businessdomains_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Название', verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание')),
                ('color', models.TextField(blank=True, default='#fff', help_text='Цвет', null=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тип тэга',
                'verbose_name_plural': 'Типы тэгов',
                'db_table': 'tags_type',
            },
        ),
        migrations.AlterField(
            model_name='businessdomains',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='domains', related_query_name='domains', to='core.tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_type',
            field=models.ForeignKey(blank=True, help_text='Тип тэга', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', related_query_name='tags', to='core.tagstype', verbose_name='Тип тэга'),
        ),
    ]
